org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.4.7-hotspot

# Mod Properties
mod_id = mod_menu
mod_name = Mod Menu
mod_version = 1.0.0
mod_authors = azuban, 1foxy2, Prospector, TerraformersMC
mod_description = Adds a mod menu to view the list of installed mods. This mod is a fork of Better Modlist (https://modrinth.com/mod/better-modlist), which is a fork of Mod Menu (https://modrinth.com/mod/modmenu).
archives_base_name = ModMenu
maven_group = com.terraformersmc.mod_menu

# Minecraft / Forge Properties
mc_version = 1.12.2
forge_version = 14.23.5.2860
mcp_mappings_channel = stable
mcp_mappings_version = 39
